### ISSUE TITLE
纯小白用gpt现学理解了下这些概念，希望能跟上脚步一起学习

### ISSUE THREAD

**Issue by chenxi0226** [aeilang/gopher#15]
https://github.com/aeilang/gopher

**Comment by aeilang** [comment]
仓库写错了

**Comment by chenxi0226** [comment]
不好意思不好意思，仓库地址如下
https://github.com/[chenxi0226/safe_map](https://github.com/chenxi0226/safe_map)

**Comment by chenxi0226** [comment]
不好意思不好意思，仓库地址如下
https://github.com/chenxi0226/safe_map
